sudo: true
dist: trusty
language: python
python:
- '3.5'
services:
- docker
env:
- TOX_ENV=安裝
- TOX_ENV=docker安裝
- TOX_ENV=flake8
install:
- pip install tox
branches:
  only:
  - master
script:
- tox -e $TOX_ENV

