sudo: false
dist: trusty
language: python
python:
- '3.4'
- '3.5'
env:
- TOX_ENV=安裝
- TOX_ENV=flake8
install:
- pip install tox
branches:
  only:
  - master
  - /\d+\.\d+\.\d+/
script:
- tox -e $TOX_ENV

