version: '3.5'

services:
  gunicorn:
    build:
      context: .
      target: tsau2_wsgi
#      target: ki1tshoo2
    command: gunicorn hok8_bu7.wsgi --log-level debug -b 0.0.0.0:8000
    volumes:
      - sqlite3:/usr/local/sqlite3
      - im1tong2:/usr/local/hok8_bu7/資料庫影音檔案
    depends_on:
      - pyro4
      - rabbitmq
    expose:
      - "8000"
    environment:
      VIRTUAL_HOST: "xn--lhrz38b.xn--v0qr21b.xn--kpry57d"
      VIRTUAL_PORT: 8000
  huan1ik8:
    build:
      context: .
      target: tsau2_huan1ik8
    command: python3 manage.py 載入服務模型
    depends_on:
      - pyro4
  pian7sik4:
    build:
      context: .
      target: tsau2_pian7sik4
    command: celery -A hok8_bu7 worker -l info
    volumes:
      - sqlite3:/usr/local/sqlite3
      - im1tong2:/usr/local/hok8_bu7/資料庫影音檔案
    depends_on:
      - rabbitmq
  pyro4:
    build:
      context: .
      target: ki1tshoo2
    command: python3 -m Pyro4.naming -n 0.0.0.0
  rabbitmq:
    image: rabbitmq:3-management
    environment: 
      RABBITMQ_DEFAULT_USER: ti1a2
      RABBITMQ_DEFAULT_PASS: gau5tsa2
      RABBITMQ_DEFAULT_VHOST: hok8_bu7

volumes:
  sqlite3:
  im1tong2:
 
