version: '3.5'

services:
  gunicorn:
    image: i3thuan5/hok8-bu7:latest
    command: gunicorn hok8_bu7.wsgi --log-level debug -b 0.0.0.0:8000
    volumes:
      - ./local.py:/usr/local/hok8-bu7/hok8_bu7/local.py
      - sqlite3:/usr/local/hok8-bu7/sqlite3
      - im1tong2:/usr/local/hok8-bu7/資料庫影音檔案
    depends_on:
      - pyro4
      - rabbitmq
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      VIRTUAL_HOST: "xn--lhrz38b.xn--v0qr21b.xn--kpry57d"
      VIRTUAL_PORT: 8000
  huan1ik8:
    image: i3thuan5/hok8-bu7:latest
    command: python3 manage.py 載入服務模型
    volumes:
      - ./local.py:/usr/local/hok8-bu7/hok8_bu7/local.py
    depends_on:
      - pyro4
  pian7sik4:
    image: i3thuan5/hok8-bu7:kaldi
    command: celery -A hok8_bu7 worker -l info
    volumes:
      - ./local.py:/usr/local/hok8-bu7/hok8_bu7/local.py
      - ./exp:/usr/local/kaldi/egs/taiwanese/s5c/exp
      - sqlite3:/usr/local/hok8-bu7/sqlite3
      - im1tong2:/usr/local/hok8-bu7/資料庫影音檔案
      - kaldi:/usr/local/kaldi
    depends_on:
      - rabbitmq
  pyro4:
    image: i3thuan5/hok8-bu7:latest
    command: python3 -m Pyro4.naming -n 0.0.0.0
  rabbitmq:
    image: rabbitmq:3-management
    environment: 
      RABBITMQ_DEFAULT_USER: ti1a2
      RABBITMQ_DEFAULT_PASS: gau5tsa2
      RABBITMQ_DEFAULT_VHOST: hok8_bu7
  kaldi:
    image: sih4sing5hong5/pianho-e-kaldi:16.04
    command: wget https://github.com/sih4sing5hong5/kaldi/raw/aca9eca6a3429672a44a913d7f0b5d7594a69ad0/egs/taiwanese/s5c/%E6%9C%8D%E5%8B%99%E4%BE%86%E8%A9%A6nnet3.sh -O /usr/local/kaldi/egs/taiwanese/s5c/服務來試nnet3.ku.sh
    volumes:
      - kaldi:/usr/local/kaldi

volumes:
  sqlite3:
  im1tong2:
  kaldi:
 
